#pragma once
#include "Locator.h"
#include "MapManager.h"
#include "MenuManager.h"
#include "RenderManager.h"
#include "RoleManager.h"
#include "Control.h"
#include "Menu.h"
#include "Role.h"
#include "BattleManager.h"
#include "Scene.h"
#include "Implement.h"
#include "State.h"
#include "World.h"
#include "Creator.h"
#include "Terrain.h"

#include <iostream>
#include <fstream>